mainsite/urls.py
from django.urls import path
from .views import HomeView

app_name = "mainsite"

urlpatterns = [path("", HomeView.as_view(), name="home")]

permanences/urls.py
from django.urls import path
from .views import PermTableView

app_name = "permanences"

urlpatterns = [path("", PermTableView.as_view(), name="table")]

user_profile/urls.py
from django.urls import path, register_converter
from .views import UserSettingsView, UserEmailSettingsView

app_name = "user_profile"

urlpatterns = [
    path("profile", UserSettingsView.as_view(), name="profile"),
    path(
        "email_settings/<uuid:token>",
        UserEmailSettingsView.as_view(),
        name="email_settings_view",
    ),
]

mainsite/models.py
from django.db import models

# Create your models here.

mainsite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    """ Home page """

    template_name = "mainsite/home.html"

mainsite/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <title>Légulm</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0;">
    {% block extra_head %}{% endblock %}
  </head>

  <body class="{% block page-class %}{% endblock %}">
    <header>
      <h1><a href="{% url 'mainsite:home' %}">Légulm</a></h1>

      <nav>
        <ul id="navright">
          {% if user.username %}
            <li id="username">
              <a href="{% url "user_profile:profile" %}">
                <i class="fa fa-user-circle"
                   aria-hidden="true"
                   style="padding-right: 0.25em;"></i>
                {{ user.username }}
              </a>
            </li>
            <li id="logout">
              <a href="{% url "account_logout" %}">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
                Déconnexion
              </a>
            </li>

          {% else %}
            <li id="login">
              <a href="{% url "account_login" %}">
                <i class="fa fa-sign-in"
                   aria-hidden="true"
                   style="padding-right: 0.25em;"></i>
                Connexion
              </a>
            </li>
          {% endif %}
        </ul>
        <ul id="navleft">
          <li>
            <a href="{% url 'mainsite:home' %}">Accueil</a>
          </li><li>
            <a href="{% url 'permanences:table' %}">Permanences</a>
          </li>{% if user.is_staff %}<li>
            <a href="{% url 'admin:index' %}">Administration</a>
          </li>{% endif %}
        </ul>
      </nav>
    </header>

    <div id="container">
      <h1 id="pagename">
        {% block pagename %}{% endblock %}
      </h1>

      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="msg {% if message.tags %} {{ message.tags }}{% endif %}">
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %}

      <div id="content">
      {% block content %}{% endblock %}
      </div>
    </div>

  </body>
</html>